# Generated by Django 3.2.9 on 2021-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('A', 'Art'), ('B', 'Books'), ('C', 'Clothing'), ('E', 'Electronics'), ('F', 'Furniture'), ('G', 'Gaming'), ('H', 'Home'), ('M', 'Miscellaneous'), ('OC', 'Outdoor/Camping'), ('T', 'Toys')], default=('T', 'Toys'), max_length=2),
            preserve_default=False,
        ),
    ]
