# Generated by Django 3.2.9 on 2021-12-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211214_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='listing_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_comments', to='auctions.listing'),
        ),
    ]
