# Generated by Django 3.2.9 on 2021-12-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comments_listing_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='listing_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_comments', to='auctions.listing'),
        ),
    ]
