# Generated by Django 3.2.9 on 2021-12-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comments_listing_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='listing_images'),
        ),
    ]
